export type ClinicalPhrase = {
  specialty: string;
  context: string;
  text: string;
};

const general = (context: string, texts: string[]): ClinicalPhrase[] =>
  texts.map((text) => ({ specialty: "Clínica geral", context, text }));

const specialty = (name: string, texts: string[]): ClinicalPhrase[] =>
  texts.map((text) => ({ specialty: name, context: name, text }));

export const CLINICAL_PHRASES: ClinicalPhrase[] = [
  ...general("Abertura", [
    "Bom dia, eu sou o Lucas, estudante de medicina, e vou iniciar seu atendimento.",
    "Como você prefere ser chamado?",
    "Qual é o principal motivo da consulta de hoje?",
    "Além disso, existe outra preocupação que você gostaria de conversar?",
  ]),
  ...general("Queixa principal", [
    "Conte com suas palavras o que está sentindo.",
    "Quando esse sintoma começou?",
    "O início foi súbito ou aconteceu aos poucos?",
    "Esse sintoma está melhorando, piorando ou permanece igual?",
  ]),
  ...general("Caracterização", [
    "Em qual parte do corpo você sente o problema?",
    "Como você descreveria essa sensação?",
    "De zero a dez, qual é a intensidade do sintoma?",
    "O sintoma é contínuo ou aparece em alguns momentos?",
    "Existe algo que melhora o sintoma?",
    "Existe algo que piora o sintoma?",
  ]),
  ...general("Sintomas associados", [
    "Você teve febre ou calafrios?",
    "Você sentiu falta de ar, tontura ou desmaio?",
    "Você teve náuseas, vômitos ou alteração do apetite?",
    "Percebeu alguma alteração no sono, no peso ou na disposição?",
  ]),
  ...general("Antecedentes", [
    "Você tem alguma doença ou condição de saúde diagnosticada?",
    "Já precisou ser internado ou fazer alguma cirurgia?",
    "Já teve esse mesmo problema antes?",
    "Existe alguma doença importante na sua família?",
  ]),
  ...general("Medicamentos e alergias", [
    "Quais medicamentos você usa atualmente?",
    "Você sabe a dose e o horário de cada medicamento?",
    "Usou algum remédio por conta própria para esse sintoma?",
    "Você tem alergia a algum medicamento, alimento ou substância?",
    "O que acontece quando você entra em contato com essa substância?",
  ]),
  ...general("Hábitos", [
    "Você fuma ou já fumou?",
    "Você consome bebidas alcoólicas? Com que frequência?",
    "Como são sua alimentação e sua rotina de atividade física?",
    "Com quem você mora e quem ajuda nos seus cuidados?",
  ]),
  ...general("Segurança e encerramento", [
    "Neste momento, você sente dor muito forte ou dificuldade para respirar?",
    "Houve perda de consciência, fraqueza súbita ou alteração da fala?",
    "Vou repetir o que entendi para confirmar se está correto.",
    "Existe algum detalhe importante que eu ainda não perguntei?",
    "Agora vou conversar com o médico responsável e explicar os próximos passos.",
    "Você entendeu as orientações ou gostaria que eu explicasse novamente?",
    "Você tem alguma dúvida antes de encerrarmos a consulta?",
    "Obrigado por compartilhar essas informações comigo.",
  ]),

  ...specialty("Urgência e emergência", [
    "O que aconteceu imediatamente antes de você chegar ao pronto atendimento?",
    "Você está com dor no peito, falta de ar ou sensação de desmaio agora?",
    "Houve queda, acidente, pancada na cabeça ou perda de consciência?",
    "Você apresentou fraqueza de um lado do corpo ou dificuldade súbita para falar?",
    "Qual foi a última vez em que você estava bem, sem esses sintomas?",
    "Você tomou algum medicamento antes de vir ao hospital?",
  ]),
  ...specialty("Cardiologia", [
    "A dor no peito aparece no esforço ou também em repouso?",
    "A dor se espalha para o braço, as costas, o pescoço ou a mandíbula?",
    "Você sente palpitações ou percebe o coração batendo de forma irregular?",
    "Você precisa usar mais travesseiros para conseguir dormir sem falta de ar?",
    "Percebeu inchaço nas pernas ou ganho rápido de peso?",
    "Já teve infarto, arritmia, pressão alta ou insuficiência cardíaca?",
  ]),
  ...specialty("Pneumologia", [
    "Você está com tosse seca ou com catarro?",
    "Qual é a cor do catarro? Percebeu presença de sangue?",
    "A falta de ar acontece em repouso, ao caminhar ou ao deitar?",
    "Você escuta chiado no peito ou sente aperto para respirar?",
    "Já teve asma, bronquite, tuberculose ou pneumonia?",
    "Você fuma, já fumou ou se expõe a poeira e fumaça no trabalho?",
  ]),
  ...specialty("Gastroenterologia", [
    "A dor abdominal fica em qual região e se espalha para algum lugar?",
    "Você teve azia, queimação, dificuldade ou dor para engolir?",
    "Houve vômito com sangue ou fezes pretas como borra?",
    "Seu hábito intestinal mudou? Teve diarreia, prisão de ventre ou sangue nas fezes?",
    "Percebeu pele amarelada, urina escura ou fezes claras?",
    "Teve perda de peso ou redução do apetite sem intenção?",
  ]),
  ...specialty("Neurologia", [
    "A dor de cabeça começou de repente ou aumentou aos poucos?",
    "Esta é a pior dor de cabeça que você já sentiu?",
    "Você teve convulsão, desmaio ou período de confusão?",
    "Percebeu fraqueza, dormência ou alteração da coordenação?",
    "Houve alteração da visão, da fala, da memória ou do comportamento?",
    "Você tem dificuldade para caminhar ou sofreu quedas recentemente?",
  ]),
  ...specialty("Endocrinologia", [
    "Você tem sentido muita sede ou vontade de urinar várias vezes?",
    "Teve perda ou ganho de peso sem mudança na alimentação?",
    "Percebeu tremores, suor excessivo, frio ou calor fora do habitual?",
    "Como estão suas medidas de glicemia e o uso de insulina?",
    "Já teve feridas nos pés, formigamento ou alteração da visão?",
    "Você tem doença da tireoide, diabetes ou alteração do colesterol?",
  ]),
  ...specialty("Nefrologia", [
    "Percebeu redução da quantidade de urina ou espuma na urina?",
    "Teve sangue na urina, dor lombar ou inchaço no rosto e nas pernas?",
    "Já teve pedra nos rins, infecção urinária ou doença renal?",
    "Usou anti-inflamatórios, suplementos ou contraste recentemente?",
    "Como estão sua pressão arterial e o controle do diabetes?",
    "Você faz diálise? Em quais dias e quando foi a última sessão?",
  ]),
  ...specialty("Urologia", [
    "Você sente dor ou ardência para urinar?",
    "O jato urinário está fraco, interrompido ou demora para começar?",
    "Você acorda quantas vezes durante a noite para urinar?",
    "Percebeu sangue na urina ou saída de secreção pela uretra?",
    "Está com dor nos testículos, na região lombar ou abaixo do umbigo?",
    "Houve alteração da função sexual ou dificuldade de ereção?",
  ]),
  ...specialty("Infectologia", [
    "Quando a febre começou e qual foi a maior temperatura medida?",
    "Você viajou, teve contato com água de enchente ou com animais recentemente?",
    "Alguém próximo apresentou sintomas parecidos?",
    "Você teve manchas na pele, rigidez na nuca ou sensibilidade à luz?",
    "Fez uso recente de antibiótico ou ficou internado nos últimos meses?",
    "Suas vacinas estão atualizadas?",
  ]),
  ...specialty("Reumatologia", [
    "Quais articulações estão doloridas ou inchadas?",
    "A rigidez ao acordar dura quanto tempo?",
    "A dor melhora com movimento ou com repouso?",
    "Você teve feridas na boca, queda de cabelo ou sensibilidade ao sol?",
    "Percebeu mudança de cor nos dedos quando sente frio?",
    "Existe histórico de doença autoimune na família?",
  ]),
  ...specialty("Dermatologia", [
    "Quando a lesão de pele apareceu e como ela mudou desde então?",
    "A lesão coça, dói, sangra ou libera secreção?",
    "Usou algum produto, medicamento ou cosmético novo?",
    "Outras pessoas da casa apresentam coceira ou lesões parecidas?",
    "Alguma pinta mudou de tamanho, formato ou cor?",
    "Você costuma se proteger do sol?",
  ]),
  ...specialty("Hematologia", [
    "Você percebeu manchas roxas, sangramentos ou palidez?",
    "Tem cansaço, falta de ar aos esforços ou palpitações?",
    "Teve trombose, embolia ou sangramento importante anteriormente?",
    "Existe anemia, trombose ou doença do sangue na família?",
    "Recebeu transfusão de sangue alguma vez?",
    "Percebeu aumento de gânglios, febre noturna ou perda de peso?",
  ]),
  ...specialty("Oncologia", [
    "Quando recebeu o diagnóstico e quais tratamentos já realizou?",
    "Está fazendo quimioterapia, radioterapia, imunoterapia ou hormonioterapia?",
    "Teve febre, sangramento ou falta de ar depois do último tratamento?",
    "Como estão a dor, o apetite, o peso e o nível de energia?",
    "Você está conseguindo tomar os medicamentos conforme orientado?",
    "Qual é sua maior preocupação neste momento do tratamento?",
  ]),
  ...specialty("Ortopedia e traumatologia", [
    "Como aconteceu a queda, a pancada ou a torção?",
    "Você consegue apoiar o peso e movimentar a região?",
    "Percebeu deformidade, estalo, inchaço ou perda de força?",
    "Sente dormência, formigamento ou mudança de cor na extremidade?",
    "A dor piora com algum movimento específico?",
    "Já teve lesão, cirurgia ou fisioterapia nessa região?",
  ]),
  ...specialty("Ginecologia", [
    "Quando foi sua última menstruação e seus ciclos são regulares?",
    "Está com sangramento fora do período menstrual ou após relação sexual?",
    "Apresenta corrimento, coceira, odor ou dor pélvica?",
    "Sente dor durante a relação sexual?",
    "Qual método contraceptivo você utiliza?",
    "Quando realizou o último exame preventivo do colo do útero?",
  ]),
  ...specialty("Obstetrícia", [
    "De quantas semanas é a gestação e quando foi a última menstruação?",
    "Você está com sangramento, perda de líquido ou contrações?",
    "O bebê está se movimentando como de costume?",
    "Teve dor de cabeça forte, visão embaçada ou inchaço repentino?",
    "Como está o acompanhamento pré-natal e quais exames já realizou?",
    "Quantas gestações, partos, cesáreas ou perdas gestacionais você teve?",
  ]),
  ...specialty("Pediatria", [
    "Quem acompanha a criança e pode contar o que aconteceu?",
    "A criança está mamando, comendo e urinando normalmente?",
    "Teve febre? Qual foi a temperatura e como ela foi medida?",
    "As vacinas e o acompanhamento de crescimento estão atualizados?",
    "Como foram a gestação, o parto e o desenvolvimento da criança?",
    "A criança está mais sonolenta, irritada ou com dificuldade para respirar?",
  ]),
  ...specialty("Neonatologia", [
    "Com quantas semanas o bebê nasceu e qual foi o peso ao nascer?",
    "O bebê precisou de reanimação, oxigênio ou internação após o parto?",
    "Como estão a amamentação, a pega e a quantidade de mamadas?",
    "Quantas fraldas de urina e evacuações o bebê apresenta por dia?",
    "Percebeu pele amarelada, febre ou dificuldade para acordar?",
    "O teste do pezinho e as demais triagens neonatais foram realizados?",
  ]),
  ...specialty("Psiquiatria", [
    "Como está seu humor na maior parte dos dias?",
    "Como estão seu sono, apetite, energia e concentração?",
    "Você tem se sentido muito ansioso, inquieto ou com crises de medo?",
    "Em algum momento pensou em se machucar ou em não querer mais viver?",
    "Você escuta vozes ou percebe coisas que outras pessoas não percebem?",
    "Usa álcool, cigarro ou outras substâncias para lidar com o que sente?",
  ]),
  ...specialty("Geriatria", [
    "Você consegue tomar banho, vestir-se e se alimentar sem ajuda?",
    "Quem organiza seus medicamentos e seus compromissos?",
    "Teve quedas, esquecimentos ou períodos de confusão recentemente?",
    "Está usando bengala, andador, aparelho auditivo ou óculos?",
    "Como estão seu apetite, seu sono e sua convivência com outras pessoas?",
    "Você já conversou com sua família sobre preferências de cuidado?",
  ]),
  ...specialty("Otorrinolaringologia", [
    "Você está com dor de ouvido, secreção ou redução da audição?",
    "Teve zumbido, tontura ou sensação de ouvido tampado?",
    "Está com obstrução nasal, sangramento ou perda do olfato?",
    "A dor de garganta dificulta engolir líquidos ou respirar?",
    "Percebeu rouquidão persistente ou mudança na voz?",
    "Teve exposição frequente a ruído intenso?",
  ]),
  ...specialty("Oftalmologia", [
    "A alteração da visão começou de repente ou aos poucos?",
    "Você sente dor nos olhos, vermelhidão ou sensibilidade à luz?",
    "Percebe flashes de luz, moscas volantes ou uma sombra no campo visual?",
    "Houve trauma, contato com produto químico ou corpo estranho no olho?",
    "Usa óculos, lentes de contato ou colírios?",
    "Tem glaucoma, catarata, diabetes ou cirurgia ocular prévia?",
  ]),
  ...specialty("Cirurgia geral", [
    "Quando a dor começou e em qual região do abdome ela é mais forte?",
    "Você conseguiu evacuar e eliminar gases hoje?",
    "Teve vômitos, febre, distensão abdominal ou perda de apetite?",
    "Já realizou alguma cirurgia no abdome?",
    "Quando foi sua última refeição ou ingestão de líquidos?",
    "Usa anticoagulante ou teve problemas de cicatrização anteriormente?",
  ]),
  ...specialty("Anestesiologia", [
    "Você já recebeu anestesia? Teve alguma reação ou dificuldade?",
    "Existe histórico de problema grave com anestesia na sua família?",
    "Quando foi a última vez que comeu ou bebeu alguma coisa?",
    "Usa anticoagulante, insulina ou algum medicamento para emagrecer?",
    "Tem prótese dentária, dente solto ou dificuldade para abrir a boca?",
    "Apresenta ronco intenso, apneia do sono ou usa aparelho para dormir?",
  ]),
  ...specialty("Medicina de família e prevenção", [
    "Quais são seus principais objetivos de saúde neste momento?",
    "Sua pressão, glicemia e vacinação estão acompanhadas?",
    "Quando realizou os últimos exames preventivos recomendados?",
    "Como estão alimentação, atividade física, sono e saúde emocional?",
    "Existe alguma dificuldade para conseguir medicamentos ou atendimento?",
    "Você se sente seguro em casa e em seus relacionamentos?",
  ]),
  ...specialty("Cuidados paliativos", [
    "O que é mais importante para você neste momento?",
    "Qual sintoma está causando mais desconforto hoje?",
    "O que você compreendeu sobre sua condição e o tratamento?",
    "Quem você deseja que participe das decisões sobre seus cuidados?",
    "Existe algo que você teme ou que deseja evitar no tratamento?",
    "Como podemos apoiar melhor você e sua família?",
  ]),
  ...specialty("Alergia e imunologia", [
    "Qual substância parece causar a reação e quanto tempo depois ela começa?",
    "A reação causa urticária, inchaço, chiado ou dificuldade para respirar?",
    "Você já precisou usar adrenalina ou procurar uma emergência por alergia?",
    "Tem asma, rinite, dermatite ou alergia alimentar?",
    "Usou algum medicamento novo antes dos sintomas?",
    "Você carrega identificação ou medicação para uma reação grave?",
  ]),
  ...specialty("Mastologia", [
    "Quando percebeu o nódulo ou a alteração na mama?",
    "Existe dor, vermelhidão ou saída de secreção pelo mamilo?",
    "Percebeu retração da pele ou mudança no formato da mama?",
    "Quando realizou a última mamografia ou ultrassonografia?",
    "Existe histórico de câncer de mama ou ovário na família?",
    "Já realizou biópsia ou cirurgia nas mamas?",
  ]),
  ...specialty("Cirurgia vascular", [
    "A perna inchou ou ficou dolorida de forma repentina?",
    "A dor nas pernas aparece ao caminhar e melhora ao parar?",
    "Percebeu ferida que não cicatriza ou mudança de cor nos pés?",
    "Já teve trombose, embolia, varizes ou cirurgia vascular?",
    "Usa anticoagulante ou meias de compressão?",
    "Sente o pé frio, dor intensa ou perda de sensibilidade agora?",
  ]),
  ...specialty("Proctologia", [
    "Você percebeu sangue vivo nas fezes ou no papel higiênico?",
    "Sente dor, coceira ou presença de caroço na região anal?",
    "Houve mudança no formato ou na frequência das evacuações?",
    "Você precisa fazer muita força para evacuar?",
    "Teve perda de peso ou anemia sem explicação?",
    "Existe histórico de câncer de intestino ou pólipos na família?",
  ]),
  ...specialty("Medicina do trabalho", [
    "Qual é sua ocupação e quais tarefas realiza durante o dia?",
    "Você se expõe a ruído, poeira, produtos químicos ou esforço repetitivo?",
    "Os sintomas melhoram nos dias em que não trabalha?",
    "Você utiliza os equipamentos de proteção disponíveis?",
    "Houve acidente ou mudança recente nas condições de trabalho?",
    "Como os sintomas interferem na sua capacidade de trabalhar?",
  ]),
  ...specialty("Sexologia e saúde sexual", [
    "Posso fazer algumas perguntas sobre sua saúde sexual?",
    "Você tem relações com homens, mulheres ou pessoas de outros gêneros?",
    "Você utiliza preservativo e realizou testes para infecções sexualmente transmissíveis?",
    "Sente dor, redução do desejo ou alguma dificuldade durante as relações?",
    "Existe possibilidade de gravidez neste momento?",
    "Você se sente seguro e respeitado nas suas relações?",
  ]),
];

export const CLINICAL_SPECIALTIES = Array.from(
  new Set(CLINICAL_PHRASES.map((phrase) => phrase.specialty)),
);

export const phrasesForSpecialty = (specialtyName: string) =>
  CLINICAL_PHRASES.filter((phrase) => phrase.specialty === specialtyName);
